"""Demo-only hotel photography.

The property's own photographs are not licensed to this site. For Jon's preview we want the
page to look like a finished site, so the old site's images are pulled from the domain he now
owns, resized, and **stamped** with a banner saying what they are. The stamp is burned into
the pixels so it survives a screenshot, and the pages that use them carry `demo = true`, which
the release gate refuses to build. Replace them with a licensed feed before launch.

    python tools/demo_photos.py          -> assets/img/demo/*.webp (+ -700) and the TOML block
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "capture" / "images"
OUT = ROOT / "assets" / "img" / "demo"
FONTS = Path("C:/Windows/Fonts")
BANNER_JA = "参考画像：旧サイトから取得したデモ用の画像です"
BANNER_EN = "REFERENCE ONLY — NOT LICENSED FOR PUBLICATION"

# file in capture/images -> (photo key, alt, caption)
PHOTOS = [
    ("D2iBVUUcKTobJgl1566920084_1566920168.jpg", "hm-exterior",
     "通りに面した建物の入口。看板と、地階へ下りる階段", "建物の入口（浅草橋2丁目）"),
    ("oWWyITOcISx7oeh1566961828_1566961997.jpg", "hm-lobby",
     "フロントカウンターと観葉植物の置かれたロビー", "フロント"),
    ("IMG_2594-3.jpg", "hm-stair",
     "地階のフロントへ下りる、曲線を描いた階段", "フロントへ下りる階段"),
    ("IMG_2558-2.jpg", "hm-single",
     "ベッドと机、鏡のある客室", "客室（机まわり）"),
    ("IMG_2565-2.jpg", "hm-double",
     "ダブルベッドと窓際の机がある客室", "客室（ダブル）"),
    ("IMG_2538-2.jpg", "hm-twin",
     "ベッドが2台並び、壁に絵の掛かった客室", "客室（ツイン）"),
    ("IMG_2546.jpg", "hm-bath",
     "洗面台と浴槽、シャワーカーテンのあるユニットバス", "ユニットバス"),
    ("IMG_2277-2.jpg", "hm-restaurant",
     "木のカウンター席が並ぶ、館内の食事処", "館内の食事処"),
]


def font(size: int, weight: int = 600) -> ImageFont.FreeTypeFont:
    f = ImageFont.truetype(str(FONTS / "NotoSansJP-VF.ttf"), size)
    try:
        f.set_variation_by_axes([weight])
    except Exception:
        pass
    return f


def stamp(im: Image.Image) -> Image.Image:
    """A banner across the bottom, sized to the image so both widths read the same."""
    im = im.convert("RGB")
    w, h = im.size
    bar = max(30, round(h * 0.085))
    strip = Image.new("RGBA", (w, bar), (24, 27, 39, 235))
    d = ImageDraw.Draw(strip)
    f1, f2 = font(round(bar * 0.36)), font(round(bar * 0.26), 500)
    # Centred, because the page crops these images to a fixed ratio and would clip a
    # left-aligned banner's first characters.
    d.text((w / 2 - f1.getlength(BANNER_JA) / 2, bar * 0.14), BANNER_JA, font=f1, fill=(255, 255, 255))
    d.text((w / 2 - f2.getlength(BANNER_EN) / 2, bar * 0.58), BANNER_EN, font=f2, fill=(214, 172, 164))
    im.paste(strip, (0, h - bar), strip)
    return im


def emit(path: Path, key: str, alt: str, caption: str) -> str:
    im = Image.open(path)
    im.load()
    out = []
    for width in (1400, 700):
        v = im.copy()
        v.thumbnail((width, width * 2), Image.LANCZOS)
        v = stamp(v)
        name = f"{key}.webp" if width == 1400 else f"{key}-700.webp"
        v.save(OUT / name, "WEBP", quality=74, method=5)
        out.append(v.size)
    w, h = out[0]
    return f"""[{key}]
src = "/assets/img/demo/{key}.webp"
alt = "{alt}"
caption = "{caption}"
credit = "画像：旧hotelmercury.jpの掲載画像（デモ用・差し替え前提）"
licence = "未許諾（デモ表示のみ）"
licence_url = ""
source = "https://hotelmercury.jp/"
origin = "旧サイト"
demo = true
width = {w}
height = {h}
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    blocks = []
    for fn, key, alt, caption in PHOTOS:
        p = SRC / fn
        if not p.exists():
            sys.exit(f"missing {p} — run the capture first")
        blocks.append(emit(p, key, alt, caption))
    (ROOT / "content" / "photos-demo.toml").write_text(
        "# GENERATED by tools/demo_photos.py — scraped, stamped, demo only. Do not release.\n"
        "# Delete this file and its entries when licensed photography is wired in.\n\n"
        + "\n".join(blocks), encoding="utf-8")
    print(f"{len(blocks)} demo photos -> {OUT} + content/photos-demo.toml")


if __name__ == "__main__":
    main()
